<%
  request.setAttribute("pageTitle", "Community Questions");
%>
<%@ include file="includes/header.jsp" %>
<div class="community-page medium-page">
  <header class="page-hero community-heading"><div><div class="eyebrow">/ COMMUNITY · REAL INTERVIEWS</div><h1>Community Questions</h1><p>Learn from scenarios shared by interview candidates, with practical coaching notes to help you prepare.</p></div><button class="button button-primary">✦ Submit a question</button></header>
  <section class="panel-card submission-form"><div class="panel-heading"><h2>Share an interview scenario</h2><span>Lightbulb</span></div><label>Question or scenario *<textarea rows="4" placeholder="What were you asked, and what context made it challenging?"></textarea></label><div class="form-grid four"><label>Technology *<select><option>Choose a technology</option><option>Java</option><option>React</option><option>AWS</option></select></label><label>Company<input placeholder="e.g. Acme"></label><label>Round / stage<select><option>Choose a stage</option><option>Technical round</option><option>System design</option></select></label><label>Difficulty<select><option>Self-rate (optional)</option><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><div class="form-actions"><span>Pending submissions are reviewed before publishing.</span><button class="button button-outline">Send for review</button></div></section>
  <div class="filter-grid"><select><option>All technologies</option></select><input placeholder="Filter by company"><select><option>All difficulties</option></select><select><option>Newest first</option><option>Most helpful</option></select></div><p class="muted mono">3 published questions</p>
  <article class="question-list-card"><div class="question-tags"><b>React</b><span>medium</span><span>technical round</span></div><h2>How would you prevent unnecessary re-renders in a large React application?</h2><p class="warning-note">User-submitted and unverified — not officially affiliated with any company.</p><div class="answer-preview"><b>What it tests</b><p>Component boundaries, memoization, stable references, and measuring before optimizing.</p><b>A practical approach</b><p>Start with the profiler, then consider React.memo, useMemo, useCallback, and state colocation.</p></div><div class="question-footer"><span>Submitted by Alex Morgan · 2 days ago</span><span><button class="vote">↑ 42</button><button class="vote">↓ 3</button><button class="vote">⚑</button></span></div></article>
  <article class="question-list-card"><div class="question-tags"><b>AWS</b><span>hard</span><span>system design</span></div><h2>Design a multi-region deployment strategy for a latency-sensitive API.</h2><div class="question-footer"><span>Submitted by CloudRunner · 5 days ago</span><span><button class="vote">↑ 31</button><button class="vote">↓ 1</button><button class="vote">⚑</button></span></div></article>
</div>
<%@ include file="includes/footer.jsp" %>